CREATE DATABASE IF NOT EXISTS auth_ms_db;
CREATE DATABASE IF NOT EXISTS discipline_ms_db;
CREATE DATABASE IF NOT EXISTS study_tracker_ms_db;
CREATE DATABASE IF NOT EXISTS study_gamification_ms_db;
CREATE DATABASE IF NOT EXISTS study_planner_ms_db;