server:
  port: 8083

spring:
  application:
      name: STUDY-TRACKER-MS
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    jpa:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
      show-sql: true

  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
