services:
  mysql-db:
    image: mysql:8.0.34
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=auth_ms_db
      - TZ=America/Sao_Paulo
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - istudy-network

  eureka-server:
    build: ./iStudy-services/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - istudy-network

  api-gateway:
    build: ./iStudy-services/api-gateway
    container_name: api-gateway
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - istudy-network

  auth-ms:
    build: ./iStudy-services/auth-ms
    container_name: auth-ms
    env_file:
      - .env
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - DB_URL=jdbc:mysql://mysql-db:3306/auth_ms_db
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      api-gateway:
        condition: service_started
    networks:
      - istudy-network

  discipline-ms:
    build: ./iStudy-services/discipline-ms
    container_name: discipline-ms
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - DB_URL=jdbc:mysql://mysql-db:3306/discipline_ms_db
      - DB_USER=root
      - DB_PASSWORD=root
      - SPRING.RABBITMQ.HOST=rabbitmq
      - SPRING.RABBITMQ.PORT=5672
      - SPRING.RABBITMQ.USERNAME=guest
      - SPRING.RABBITMQ.PASSWORD=guest
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      api-gateway:
        condition: service_started
    networks:
      - istudy-network

  study-tracker-ms:
    build: ./iStudy-services/study-tracker-ms
    container_name: study-tracker-ms
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - DB_URL=jdbc:mysql://mysql-db:3306/study_tracker_ms_db
      - DB_USER=root
      - DB_PASSWORD=root
      - SPRING.RABBITMQ.HOST=rabbitmq
      - SPRING.RABBITMQ.PORT=5672
      - SPRING.RABBITMQ.USERNAME=guest
      - SPRING.RABBITMQ.PASSWORD=guest
    depends_on:
      mysql-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
      api-gateway:
        condition: service_started
    networks:
      - istudy-network

  study-gamification-ms:
    build: ./iStudy-services/study-gamification-ms
    container_name: study-gamification-ms
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - DB_URL=jdbc:mysql://mysql-db:3306/study_gamification_ms_db
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      api-gateway:
        condition: service_started
    networks:
      - istudy-network

  study-planner-ms:
    build: ./iStudy-services/study-planner-ms
    container_name: study-planner-ms
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - DB_URL=jdbc:mysql://mysql-db:3306/study_planner_ms_db
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      api-gateway:
        condition: service_started
    networks:
      - istudy-network

  istudy-app:
    build: ./istudy-app
    container_name: istudy-app
    ports:
    - "3000:3000"
    depends_on:
      auth-ms:
        condition: service_started
      discipline-ms:
        condition: service_started
      study-tracker-ms:
        condition: service_started
      study-gamification-ms:
        condition: service_started
    networks:
      - istudy-network

  rabbitmq:
    image: rabbitmq:3.13.7-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      timeout: 100s
      interval: 100s
      retries: 3
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASSWORD: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    networks:
      - istudy-network

networks:
  istudy-network:
    driver: bridge
