server:
  port: 8081

api:
  security:
    token:
      secret: ${JWT_KEY:my-secret-key}

spring:
  application:
    name: AUTH-MS
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth-ms-db
    username: root
    password:
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
      instance:
        prefer-ip-address: false
        hostname: localhost

