server:
  port: 8085

spring:
  application:
    name: STUDY-PLANNER-MS
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: rabbitmq

rabbitmq:
  exchange:
    user-deleted-events: user.deleted.fanout

  queue:
    user-deleted: deleted.planners.data

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
