spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - DELETE
            allowedHeaders: "*"
      routes:
        - id: auth-ms
          uri: lb://AUTH-MS
          predicates:
            - Path=/auth/**
        - id: auth-ms-users
          uri: lb://AUTH-MS
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
        - id: discipline-ms
          uri: lb://DISCIPLINE-MS
          predicates:
            - Path=/disciplines/**
          filters:
            - AuthenticationFilter
        - id: study-tracker-ms
          uri: lb://STUDY-TRACKER-MS
          predicates:
            - Path=/studies/**
          filters:
            - AuthenticationFilter
        - id: study-gamification-ms
          uri: lb://STUDY-GAMIFICATION-MS
          predicates:
            - Path=/games/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}