spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-ms
          uri: lb://AUTH-MS
          predicates:
            - Path=/auth/**
        - id: auth-ms-users
          uri: lb://AUTH-MS
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
        - id: discipline-ms
          uri: lb://DISCIPLINE-MS
          predicates:
            - Path=/disciplines/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}