ALTER TABLE disciplines
MODIFY COLUMN category ENUM(
    'EXACT_SCIENCES',
    'HUMAN_SCIENCES',
    'BIOLOGICAL_SCIENCES',
    'SOCIAL_SCIENCES',
    'HEALTH_SCIENCES',
    'ARTS_AND_HUMANITIES'
) NOT NULL;
